title: repo.GNUSlashLinux
description: Official GNUSlashLinux Package Repository

# Lädt das Konsolen-Theme
remote_theme: b2a3e8/jekyll-theme-console

# Schaltet das Design exakt auf die Nord-Farbpalette um
style: nord

plugins:
  - jekyll-remote-theme

# Fügt das Copyright und den Link zur Hauptseite im Footer hinzu
footer: "Copyright © 2026 [GNUSlashLinux](https://www.gnuslashlinux.com) | Powered By [Alien-Tec](https://www.alien-tec.com) | Alle Rechte vorbehalten."
